# Generated by Django 3.1.5 on 2021-02-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachscp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCP_PolicyId', models.CharField(max_length=30)),
                ('SCP_TargetId', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='createaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_Emails', models.CharField(max_length=30)),
                ('list_of_Names', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='createscp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCP_Description', models.CharField(max_length=30)),
                ('SCP_Name', models.CharField(max_length=30)),
                ('Document_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='listOU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OU_parentId_list', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='listroot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootId', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='moveaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountId', models.CharField(max_length=30)),
                ('DestinationId', models.CharField(max_length=30)),
                ('SourceId', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='createou',
            name='ParentId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='createou',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
