# Generated by Django 3.1.5 on 2021-02-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20210210_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachscp',
            name='SCP_PolicyId',
        ),
        migrations.RemoveField(
            model_name='attachscp',
            name='SCP_TargetId',
        ),
        migrations.RemoveField(
            model_name='listou',
            name='OU_parentId_list',
        ),
        migrations.AddField(
            model_name='attachscp',
            name='AccountId',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='attachscp',
            name='SCPPolicyId',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='listou',
            name='ParentIdlistou',
            field=models.TextField(default='', editable=False, max_length=30),
        ),
    ]
