# Generated by Django 3.1.5 on 2021-02-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20210211_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createaccount',
            old_name='list_of_Emails',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='createaccount',
            old_name='list_of_Names',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='createou',
            old_name='name',
            new_name='OUname',
        ),
    ]
